version: '3.8'

services:
  nginx:
    container_name: nginx
    build: requirements/NginX/
    image: nginx:1.01
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "wordpress_volume:/var/www/html"
    depends_on:
      - wordpress
    networks:
      frontend: {}

  wordpress:
    container_name: wordpress
    build: requirements/wordpress/
    image: wordpress:1.01
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - "wordpress_volume:/var/www/html"
    depends_on:
      - mariadb
    networks:
      frontend: {}
      backend: {}
    environment:
      - INCEPTION_MYSQL_HOST
      - WP_DATABASE_NAME
      - WP_DATABASE_USR
      - WP_DATABASE_PWD
      - DOMAIN_NAME
      - WP_TITLE
      - WP_ADMIN_USR
      - WP_ADMIN_PWD
      - WP_ADMIN_EMAIL
      - WP_USR
      - WP_PWD
      - WP_EMAIL
  
  mariadb:
    container_name: mariadb
    image: mariadb:1.01
    build: requirements/mariaDB/
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "mariadb_volume:/var/lib/mysql"
    networks:
      backend: {}
    environment:
      - INCEPTION_MYSQL_ROOT_PWD
      - WP_DATABASE_NAME
      - WP_DATABASE_USR
      - WP_DATABASE_PWD

networks:
  frontend: {}
  backend: {}

volumes:
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/website
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/mariadb